### ISSUE TITLE
Listenansicht: Job ausblenden

### ISSUE THREAD

**Issue by lizardat** [Xirdion/contao-jobposting-bundle#17]
In der Listenansicht erzeugt der Klick auf "Ausblenden" (Auge) zu einer Fehlermeldung:

`Internal Server Error
Was ist das Problem?

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'published' at row 1`

Das Deaktivieren auf der Einstellungs-Seite des jeweiligen Jobs funktioniert jedoch.

**Comment by lizardat** [comment]
Ein ähnliches Problem tritt auf, wenn man in der Listenansicht das "Job hervorheben" wieder wegklickt:

`An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `mietbox_db2`.`tl_job`.`featured` at row 1`

Zusätzlich werden bei uns ALLE neuen Einträge mit dem Datum "1970-01-01" abgespeichert - erst ein Überschreiben in den Einstellungen mit einem anderen Datum ändert dies.

**Comment by Xirdion** [comment]
Hi @lizardat 
Thanks for the report.
I haved fixed the issue in version 1.0.15.
Don't forget to adjust your composer.json file to require this package with the new vendor name: `xirdion/contao-jobposting-bundle`
